### PR TITLE
Move to 2.0.2 and add option to filter on ip6

### PR DESCRIPTION
**Pull request by beiske**

### CODE REVIEW

**Comment by xuzha** [comment]
LGTM

**Comment by hub-cap** [comment]
Do we want to get fancy with the shield example? I really liked how simple it was, and users can do this if they like. I really like the simpleness of the shield example, so a user does not get bogged down with all the extra fancy stuff.

**Comment by beiske** [comment]
@hub-cap I think the complexity is justified. Future support tickets may prove me wrong, but there has been a few issues with people not being able to connect over ipv6, even though it is resolved by their DNS service. The default has not changed and in order to make things appear simpler, we could skip adding it to the readme. Sort of just leaving some breadcrumbs for future users to debug their connection trouble.

Also this change adds all ip adresses of the ELB and not just the first one resolved. It also suggests that the domain name is resolved at connection time only. However adding logic to resolve the DNS again, should not be included in this example.

**Comment by cstrzadala** [comment]
Code LGTM

I agree with @beiske to show the added ipv6 details. The code is not really that complex, fairly easy to make it more simple if your use-case requires it and this does give users more details on how to setup ipv6.

At most, I'd add some more comments or README details to explain the code if we feel it is too complex.

**Pull request merged**
